apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-main-pv
  labels:
    type: local
    app: postgres-main
spec:
  storageClassName: manual 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"