apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-main-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-main
  template:
    metadata:
      labels: 
        app: postgres-main
    spec:
      containers:
        - name: postgres-main
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-main-secret
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-main-pv-storage
      volumes: 
        - name: postgres-main-pv-storage
          persistentVolumeClaim:
            claimName: postgres-main-claim