apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-main-claim
  labels: 
    app: postgres-main
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
